config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  post '/rate' => 'rater#create', :as => 'rate'

  resources :offers do
    resources :messages
  end
  
  resources :charges, only: [:index, :new, :create]
  # resource :booking
  resources :tours do

  end
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#page"

end

app/models/tour.rb
class Tour < ApplicationRecord
  include ImageUploader[:image]
  belongs_to :user
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :bookings
  has_many :messages
  is_impressionable
  validate :start_date_cannot_be_in_the_past, :headline_length


 def start_date_cannot_be_in_the_past
   if start_date.present? && start_date < Date.today
     errors.add(:start_date, "Can't be in the past")
   end
 end

 def headline_length
   if description.length > 30
     errors.add(:description, "has a 30 character max, its more of a headline")
   end
 end

 def self.search(search)
  where("title ILIKE ? OR description ILIKE ? OR bio ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
end

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_tour, only: [:show, :edit, :update, :destroy]
  impressionist :actions=>[:show]
  before_action :require_permission, only: :edit

  def require_permission
    if current_user != Tour.find(params[:id]).user
      redirect_to root_path
    end
  end





  # GET /tours
  # GET /tours.json
  def index

    @tours = Tour.all
    if params[:search]
      @tours = Tour.search(params[:search]).order("created_at DESC")
    else
      @tours = Tour.all.order("created_at DESC")
    end



    @cal = Calendar
    puts "hello #{params}"
  end

  # GET /tours/1
  # GET /tours/1.json
  def show


    @bookings = Booking.where(tour_id: params[:id])
    @offers = Offer.where(tour_id: params[:id])
    @offer = Offer.new
    @cal = Calendar
    @booking  = Booking.new

    @days =((@tour.end_date.to_date - @tour.start_date.to_date).to_i)+1
    @impressions = @tour.impressionist_count

    @temp = Booking.where(tour_id: @tour.id)

    @max  = find_max(@offers)
    @h_offer = @offers
  end

  # GET /tours/new
  def new
    @tour = Tour.new
  end

  # GET /tours/1/edit
  def edit
  end

  # POST /tours
  # POST /tours.json
  def create

    temp_genres = params[:tour][:genres]
    puts "#{temp_genres}".green

    @tour = Tour.new(tour_params)
    @tour.user = current_user
    @tour.country = 'Australia'

    temp_genres.each{|genre_id|
      @tour.genres << Genre.find(genre_id) unless genre_id.blank?
    }

    respond_to do |format|
      if @tour.save
        format.html { redirect_to @tour, notice: 'Tour was successfully created.' }
        format.json { render :show, status: :created, location: @tour }
      else
        format.html { render :new }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tours/1
  # PATCH/PUT /tours/1.json
  def update

    @tour.genres = [] unless params[:tour][:genres].count == 1

    temp_genres = params[:tour][:genres]
    temp_genres.each{|genre_id|
      @tour.genres << Genre.find(genre_id) unless genre_id.blank?
    }

    respond_to do |format|
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { render :show, status: :ok, location: @tour }
      else
        format.html { render :edit }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tours/1
  # DELETE /tours/1.json
  def destroy
    @tour.destroy
    respond_to do |format|
      format.html { redirect_to tours_url, notice: 'Tour was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tour
      @tour = Tour.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tour_params
      params.require(:tour).permit(:user_id, :title, :description,  :image, :bio, :start_date, :end_date, :min_cost, :max_cost)
    end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/_booking.html.erb
<div class="rics-little-div">


<%= form_with(model: @booking, local: true) do |form| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :tour_id,  :value => tour_id%>
  </div>

  <div class="field">
    <div class="label">
      <%= form.label :date %>
    </div>
    <%= form.date_select :date, start_year:  @tour.start_date.year,end_year:  @tour.start_date.year, use_month_numbers: true,  id: :booking_date %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

</div>

app/views/tours/_form.html.erb
<%= form_with(model: tour, local: true) do |form| %>
  <% if tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% tour.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="tour-form">
  <div class="field profile-field">
    <%#= form.label :title %>
    <%= form.text_field :title, id: :tour_title, placeholder: "Tour title" %>
  </div>

  <div class="field profile-field">
    <%#= form.label :description %>
    <%= form.text_field :description, id: :tour_description , placeholder: "Tour headline " %>
  </div>



  <div class="field profile-field">
    <%= form.label "Add Tour image" %>
    <%= form.file_field :image, id: :tour_image_data %>
  </div>

  <div class="field profile-field">
    <%#= form.label :bio %>
    <%= form.text_area :bio, id: :tour_bio, placeholder: "Biography and tour description" %>
  </div>




  <div class="field profile-field">

<div class="" style="border:0.5px solid #ccc;">

<%= form.label :start_date %><br>
<%= form.date_select :start_date, id: :tour_start_date %></div>
<div class="" style="border:0.5px solid #ccc;">
  <%= form.label :end_date %> <br>
  <%= form.date_select :end_date, id: :tour_end_date%>
</div>

  </div>

  <div class="field profile-field">
    <%= form.label :min_cost %>
    <%= form.number_field :min_cost, id: :tour_min_cost, placeholder: "Min cost" %>
<br>
    <%= form.label :max_cost %>
    <%= form.number_field :max_cost, id: :tour_max_cost, placeholder: "Max cost" %>
  </div>

  <div class="field">
    <%= form.label :genres %>
    <%= form.collection_select(:genres, Genre.order(:name),:id,:name,{}, {multiple: true, include_blank: false}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


</div>
<% end %>

app/views/tours/_offer_form.html.erb
<div class="rics-little-div">
<%= form_with(model: offer, local: true) do |form| %>
  <% if offer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(offer.errors.count, "error") %> prohibited this offer from being saved:</h2>
      <ul>
      <% offer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= form.hidden_field :tour_id, :value => tour_id %>


  <div class="field">
    <div class="label">
      <%= form.label :date %>
    </div>
    <%= form.date_select :date, start_year:  @tour.start_date.year,end_year:  @tour.start_date.year, id: :offer_date %>
  </div>

  <div class="field">
    <div class="label">
      <%= form.label :price %>
    </div>
    <%= form.number_field :price, id: :offer_price %>
  </div>

  <div class="field">
    <div class="label">
    <%= form.label :location %>
  </div>
    <%= form.text_field :location, id: :offer_location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/tours/edit.html.erb
<h1>Editing Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Show', @tour %> |
<%= link_to 'Back', tours_path %>

app/views/tours/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tours</h1>

<%= form_tag(tours_path, :method => "get", id: "search_genre") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<%puts "#{@tours.inspect}".green%>
<%if @tours.count < 1%>
  <%#@tours = @tours.sort_by{|tour|tour.start_date}%>
<%end%>
    <% @tours.each do |tour| %>
    <%=link_to tour_path(tour.id), class: "tour-link" do%>
      <div class="tour">
        <div class="item title tour-info">
          <p> <%= tour.title %></p>
        </div>
        <div class="item agent-logo tour-info">
        <%if tour.image_url%>
          <%= image_tag tour.image_url, class: "a-logo right-fade"%>
        <%end%>
        </div>
        <div class="item headline tour-info"><%= tour.description %></div>

        <div class="item contact tour-info right-fade"><%=tour.user.profile.brand%></div>
        <div class="item dates tour-info"><%= tour.start_date.strftime("%-d/%-m/%y") %> to <%= tour.end_date.strftime("%-d/%-m/%y") %> </div>
        <div class="item price tour-info">$<%= tour.min_cost %> to
            $<%= tour.max_cost %></div>
        <div class="item space tour-info right-fade">
          <!-- ===================week======================== -->
                <div class="week ">
                  <div class="week-title">
                    <%if tour.start_date.strftime("%B")==tour.end_date.strftime("%B")%>
                      <%= tour.start_date.strftime("%B") %> <%= tour.start_date.strftime("%Y") %>
                    <%else%>
                      <%= tour.start_date.strftime("%b") %>  to   <%= tour.end_date.strftime("%b") %> <%= tour.end_date.strftime("%Y") %>
                    <%end%>
                  </div>

                  <div class="heading sTot">Sun to Thu</div>
                  <div class="heading">Fri</div>
                  <div class="heading">Sat</div>

                  <%cal =  @cal.new(tour.start_date, tour.end_date)%>
                  <%cal.createCalendar%>
                  <%@list = []%>

                    <%temp = Booking.where(tour_id: tour.id)%>

                    <%temp.each{|i|%>
                      <%@list << i.date%>
                      <%}%>
                  <%cal.bookDays(@list)%>
                  <%#cal.bookDays(
                  DateTime.new(2018, 1, 11),DateTime.new(2018, 1, 12),DateTime.new(2018, 1, 10),DateTime.new(2018, 1, 14),DateTime.new(2018, 1, 13))%>

                  <%#cal.displayCalendar.html_safe%>

                  <%=cal.displayWeek.html_safe%>
                  </div>

          <!-- ===================week======================== -->
        </div>


      </div>
    <%end%>
    <div class="development">
      <%= link_to 'Show', tour %>
      <%= link_to 'Edit', edit_tour_path(tour) %>
      <%= link_to 'Destroy', tour, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div>











    <% end %>

<br>
<%= link_to 'New Tour', new_tour_path %>

app/views/tours/new.html.erb
<h1>New Tour</h1>

<%= render 'form', tour: @tour %>

<%= link_to 'Back', tours_path %>

app/views/tours/show.html.erb
  <div class="show-tour">
    <div class="show-image right-fade">
      <img class="show-img" src=" <%= @tour.image_url %>" alt="">
    </div>

    <div class="the-tour">

      <div class="show-title item ">
        <strong><%= @tour.title.capitalize %>
        </strong>
      </div>
        <div class="show-agent-logo item">
      <%=link_to profile_path(id: @tour.user.profile.id)do %>
          <%if @tour.user.profile.image_url != nil%>
            <%= image_tag @tour.user.profile.image_url, class: "show-agent-logo-img item"%>
          <%end%>
        </div>
      <%end%>
        <div class="agent-brand item right-fade">
        <h6>  <%= @tour.user.profile.brand %> </h6>
        </div>


        <%if @tour.user_id != current_user.id%>
          <div class="offers item right-fade">
          </div>
        <%elsif @tour.user_id == current_user.id%>
          <%=link_to offers_path, class: "offers item right-fade" do%>
            <div>
              <p> <%=@offers.count%> <br> Offers</p>
              <br>

              <%if @max.class != String %>
              <p>Highest offer <br> $<%= @max %></p>
              <%end%>
            </div>
            <div>
              <p>Bookings <span style="color:red" ><%=@bookings.count%> <br></span> available <span style="color:green" ><%=@days-(@bookings.count)%> </span> </p>
            </div>

            <div >
              <p>   <%=@impressions%> <br> views</p>
            </div>
          <%end%>
        <%end%>

      <a class="show-make-offer item" href="#offer-form">
        <div class="">
          <%if @tour.user_id != current_user.id%>
            <h5>Make a Offer</h5>
          <%else%>
            <h3>Book Dates</h3>
          <%end%>
        </div>
      </a>
      <div class="show-headline item">
        <%= @tour.description %><br>
        <h6> <% @tour.genres.each_with_index do |genre, index| %>
          <%if index == @tour.genres.count-1%>
              <%= genre.name%>
            <%elsif%>
              <%= genre.name + ", "%>
            <%end%>
        <%end%></h6>
      </div>

      <div class="show-price item">
        <h5>
        $ <%= @tour.min_cost %> to $ <%= @tour.max_cost %></h5>
      </div>
      <div class="bio item right-fade-x5">
        <%= @tour.bio %>
      </div>

      <!-- ===================calendar======================== -->
            <div class="cal item">
              <div class="cal-title">
                <%if @tour.start_date.strftime("%B")==@tour.end_date.strftime("%B")%>
                  <%= @tour.start_date.strftime("%B") %> <%= @tour.start_date.strftime("%Y") %>
                <%else%>
                  <%= @tour.start_date.strftime("%B") %>  to   <%= @tour.end_date.strftime("%B") %> <%= @tour.end_date.strftime("%Y") %>
                <%end%>
              </div>
              <div class="heading">Sun</div><div class="heading">Mon</div><div class="heading">Tue</div><div class="heading">Wed</div><div class="heading">Thu</div><div class="heading">Fri</div><div class="heading">Sat</div>
              <%cal =  @cal.new(@tour.start_date, @tour.end_date)%>
              <%cal.createCalendar%>
              <%@list = []%>
                <%@temp = Booking.where(tour_id: @tour.id)%>
                <%@temp.each{|i|%>
                  <%@list << i.date%>
                  <%}%>
              <%cal.bookDays(@list)%>
              <%# puts "#{cal.cal}".green%>
              <%=cal.displayCalendar.html_safe%>
            </div>
      <!-- ===================calendar======================== -->

    </div>

    <div class="order-render" id="offer-form">
      <%if @tour.user_id != current_user.id%>
      <p> Submit an offer </p>
      <div class="offer-form">
        <%= render 'offer_form', tour_id: @tour.id, offer: @offer %>
      </div>
      <%elsif @tour.user_id == current_user.id%>
      <p>Book Date</p>
      <%=render "booking",tour_id: @tour.id, offer: @offer %>


    </div>
  </div><!-- the-tour -->
<div class="footer fade-right-x5">
  <%= link_to 'Edit Bookings', bookings_path %>
  <%= link_to 'Edit Tour', edit_tour_path(@tour) %>
      <%end%>
</div>
<%= link_to 'Back', tours_path, class: "white" %>