config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  post '/rate' => 'rater#create', :as => 'rate'

  resources :offers do
    resources :messages
  end
  
  resources :charges, only: [:index, :new, :create]
  # resource :booking
  resources :tours do

  end
  resources :profiles
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#page"

end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :tour

  validate :date_must_in_range, :date_is_in_past
  validates :date, :presence => true, :uniqueness => true

  def date_is_in_past
    if date < Date.today
      errors.add(:date, " is in past")
    end
  end

 def date_must_in_range
   if date < tour.start_date.to_date || date > tour.end_date.to_date
     errors.add(:date, "Outside of date range")
   end
 end


end

app/models/calendar.rb
class Calendar
  require 'date'
  require 'colorize'
  def initialize(start_day, end_day)
    @start_day =start_day
    @end_day   =end_day
    @num_days = @end_day.strftime('%-j').to_i - @start_day.strftime('%-j').to_i
    @cal
    @week
  end
  attr_accessor :start_day, :end_day, :num_days, :cal, :week

  def self.all
    ObjectSpace.each_object(self).to_a
  end

  #makes the calendar entrys
  def createCalendar
    num_days = @num_days
    cal = []
    # add blank day for each day before days (except sunday)
    (0..@start_day.wday-1).each{cal << ["noDay", ""]}
    day = start_day

    (1..num_days+1).each{|i|
      cal << ["day", day, true]
      day= day + 1.days
    }
    # puts cal
    @cal = cal
  end

  def bookDays(bookedDays)
    puts "#{bookedDays[0].class}".green

    # bookedDays= bookedDays[0] if

    if bookedDays
      dates = @cal
      dates.each{|d|
        bookedDays.each{|b|
          if d[1] == b
             d[2] = false
          end
        }
      }
    end
    @cal = dates

  end

#for indivdual offer days
  def offerDay(offerDay)
    puts "#{offerDay.class}".green

    if offerDay
      dates = @cal
      dates.each{|d|
        if d[1] == offerDay
          d[2] = 2
        end
      }
    end
    @cal = dates

  end

  def displayCalendar
    divs = ""
    (@cal).each{|i|
      if i[2] == true
        divs +=   "<div class='" + "day'" +  "> <p> #{i[1].strftime('%-d')} </p></div>"
      elsif i[2] == false
        divs +=   "<div class='" + "bookedDay'" +  "> <p> #{i[1].strftime('%-d')} </p></div>"
      elsif i[2] == 2
        divs +=   "<div class='" + "yellow'" +  "> <p> #{i[1].strftime('%-d')} </p></div>"
      else
        divs +=   "<div class='" + "#{i[0]}'" +  "> </div>"
      end
      }
    divs
  end

  def displayWeek
    dates = @cal
    #count the number of days of week
    first = (@cal.count - @num_days)-1
    first = dates[first][1].to_datetime
    last = dates.last[1].to_datetime

    dates = dates[((@cal.count - @num_days)-1)..dates.length]
    #denominator
    fridays = 0
    saturdays = 0
    sunToThus = 0
    (first..last).to_a.select { |d| fridays +=1 if [5].include?(d.wday) }
     (first..last).to_a.select { |d| saturdays +=1 if [6].include?(d.wday) }
     (first..last).to_a.select { |d| sunToThus +=1 if [0,1,2,3,4].include?(d.wday) }
    total = fridays + saturdays + sunToThus

    #numerator
    bookedFridays   = 0
    bookedSaturdays = 0
    bookedSunToThus = 0
    dates.each{|d|
      if [0,1,2,3,4].include?(d[1].wday) && d[2] == false
        bookedSunToThus += 1
      elsif d[1].wday == 6 && d[2] == false
        bookedSaturdays += 1
      elsif d[1].wday == 5 && d[2] == false
        bookedFridays += 1
      end
    }
    # puts
    # puts "bookedFridays    | #{bookedFridays}"     + " fridays | #{fridays}"
    # puts "bookedSaturdays  | #{bookedSaturdays}" + " saturdays | #{saturdays}"
    # puts "bookedSunToThus  | #{bookedSunToThus}" + " sunToThus | #{sunToThus}"
    # puts " "*20 +"TOTAL  | #{total}"
    week = [(bookedSunToThus.to_f/sunToThus).round(2), (bookedFridays.to_f/fridays).round(2), (bookedSaturdays.to_f/saturdays).round(2)]
    text = ["sun to thu", "fri", "sat"]

    output = ""
    (0...3).each do |i|
      if week[i] < 0.35
        output += "<div class='" + "day'" +  ">  </div>"
        # print "#{text[i]} ".green
      elsif week[i] < 1
          output += "<div class='" + "yellow'" +  ">  </div>"
        # print "#{text[i]} ".yellow
      elsif week[i] == 1
          output += "<div class='" + "bookedDay'" +  ">  </div>"
        # print "#{text[i]} ".red
      else
          output += "<div class='" + "noDay'" +  "> </div>"
        # print "#{text[i]} ".blue
      end
    end
    #
    # puts "*"*12
    # puts week
    # print output

    @week = output
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_one :profile
  has_one :tour
end

app/models/image_uploader.rb
class ImageUploader < Shrine
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :tour
  belongs_to :offer
  belongs_to :user
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :tour
  belongs_to :user
  has_many :messages

  validate :date_must_in_range, :price_must_in_above_min_cost,:date_must_not_be_booked

 def date_must_in_range
   if date <= tour.start_date && date >= tour.end_date
     errors.add(:date, "is outside of date range")
   end
 end

 def date_must_not_be_booked
   bookings =Booking.where(tour_id: tour.id)
   bookings.each{|i|
     puts "#{i.date}".red
     if date == i.date
       errors.add(:date, " is not avaiable")
     end
   }
 end

 def price_must_in_above_min_cost
   if price < tour.min_cost
     errors.add(:price, "is outside of cost range")
   end
 end

end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/profile.rb
class Profile < ApplicationRecord
  include ImageUploader[:image]
  belongs_to :user
  has_and_belongs_to_many :genres
  scoped_search on: [:brand]
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/tour.rb
class Tour < ApplicationRecord
  include ImageUploader[:image]
  belongs_to :user
  has_and_belongs_to_many :genres
  has_and_belongs_to_many :bookings
  has_many :messages
  is_impressionable
  validate :start_date_cannot_be_in_the_past, :headline_length


 def start_date_cannot_be_in_the_past
   if start_date.present? && start_date < Date.today
     errors.add(:start_date, "Can't be in the past")
   end
 end

 def headline_length
   if description.length > 30
     errors.add(:description, "has a 30 character max, its more of a headline")
   end
 end

 def self.search(search)
  where("title ILIKE ? OR description ILIKE ? OR bio ILIKE ?", "%#{search}%", "%#{search}%", "%#{search}%")
end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :profile

 ratyrate_rater
 ratyrate_rateable "rating"
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/layouts/_nav.html.erb
<nav class="navigation">
    <div class="dropdown">
    <%= image_tag "Hamburger_icon.png", class: "hamburger"%>
    <div class="dropdown-content">
      <% if user_signed_in? %>
        <%= button_to('Logout', destroy_user_session_path, method: :delete , form_class: "login_out") %>
        <%unless params[:controller] == "profiles" && params[:action] == "new" || current_user.profile == nil%>
          <%= button_to('My Profile',profile_path(current_user.profile.id),method: :get ,form_class: "login_out")%>
        <%end%>
          <p><%=link_to 'Password', edit_user_registration_path, class: "login_out"%></p>
          <p><%=link_to 'Plans', charges_path, class: "login_out"%></p>
          <p><%=link_to 'Offers', offers_path, class: "login_out"%></p>

      <% else %>
        <div class="login-content">
        <%= button_to('Login', new_user_session_path, form_class: "login_out")%>
        </div>
      <% end %>
      </div>
    </div>

    <%=link_to root_path, class: "logo" do %>
      <%=image_tag "almost-anyone.png", class: "logo"%>
    <%end%>



    <div class="right">
      <% if user_signed_in? %>
          <%= button_to('Logout', destroy_user_session_path, method: :delete , form_class: "login_out") %>

          <h6 class="person">   <% if current_user.profile != nil %>
               <%=current_user.profile.brand[0..16]%>
            <% end %></h6>

      <% else %>
          <div>
          <%= button_to('Login', new_user_session_path, form_class: "login")  %>
          </div>
      <% end %>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlmostAnyone</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

<body>

<%=render 'layouts/nav'%>

  <div class="container">



    <%= yield %>

  </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


  </body>
</html>